apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: trojan-gfw
    files:
      - config.json

commonLabels:
  component: trojan-gfw
