apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: trojan-gfw-benchmark
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: wi1dcard/tgb
      docker:
        dockerfile: Dockerfile
    - image: wi1dcard/tgb-go
      docker:
        dockerfile: go.Dockerfile
deploy:
  kustomize:
    paths:
      - k8s
