apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: h2c
      port: 82
      targetPort: h2c
    - name: https
      port: 443
      targetPort: https
