apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert/
  - nginx/
  - trojan-gfw/

namespace: trojan-gfw-benchmark
namePrefix: tgb- # [T]rojan [G]fw [B]enchmark

commonLabels:
  app: trojan-gfw-benchmark
