apiVersion: apps/v1
kind: Deployment
metadata:
  name: trojan-server
spec:
  selector:
    matchLabels: {} # Managed by Kustomize
  template:
    metadata:
      labels: {} # Managed by Kustomize
    spec:
      volumes:
        - name: config
          configMap:
            name: trojan-server
        - name: tls-cert
          secret:
            secretName: tls-cert
      containers:
        - name: trojan-gfw
          image: wi1dcard/tgb
          imagePullPolicy: Always
          resources:
            limits:
              memory: 128Mi
              cpu: 200m
          ports:
            - name: https
              containerPort: 443
          volumeMounts:
            - mountPath: /cert
              name: tls-cert
            - mountPath: /config
              name: config
